### ISSUE TITLE
Missing Intellisense for Eloquent Relationship Methods

### ISSUE THREAD

**Issue by carlevison** [bmewburn/intelephense-docs#1]
Eloquent relationship methods aren't appearing in the autocomplete popup.

Although if you type the method out manually and hover over the method name the correct information is displayed.

![hover](https://i.imgur.com/Kcq7mzP.png)

Edit: they are showing in VSCode but not in Sublime using the LSP package.

**Comment by bmewburn** [comment]
Does Sublime LSP have a way to inspect the messages being sent/received? If it's working on vscode perhaps it's an issue with trigger characters `>`

**Comment by carlevison** [comment]
I don't think the trigger is the issue as most of the completions are there, but there are some that show in VSCode that LSP doesn't show.

After inspecting the messages I see ```isIncomplete: true```

**Comment by bmewburn** [comment]
A max of 100 suggestions is returned at which point the `isIncomplete` flag is set to true. In vscode further typing recomputes the list. Could be that LSP is not sending a further request.

**Comment by carlevison** [comment]
That is good to know thanks @bmewburn 

I was worried that it might have been a Sublime API issue.

**Comment by bmewburn** [comment]
Closing, I don't think there is anything to action in the server
