### ISSUE TITLE
node process don't use swap for memory?

### ISSUE THREAD

**Issue by wltprgm** [bmewburn/intelephense-docs#10]
_--------edit----------------------------_
My question is **"is this extension written in a way to use swap memory? because from my testing, it doesn't use swap memory"**
_---------edit ends here------------_
Hi there,

I am testing out this lsp on two of my servers.

1.  First server, in Digital Ocean $5 plan, 1GB ram + 2GB swap
   - Big project Magento 1, the RAM used by the first node process can go up to 600+MB, it finished building the cache of 37MB in /tmp/intelephense less than 1 minute.
   - New small project YIi2, cache built around 9MB

2. Second server, AWS LightSail $3.5 plan, 512MB RAM + 3GB swap
   - Same big Magento 1 project, the RAM used is always less than 400MB, never build any cache, using 100% process like forever
   - Same new small project Yii2, cache built around 9MB

I am on latest Debian Buster, using `neovim` with coc nvim plugin.

It looks like it doesn't use swap at all on both of my servers. I try command to increase nodeJS memory limit also unhelpful
[source](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory)
```
export NODE_OPTIONS=--max_old_space_size=4096,--optimize-for-size,--max-executable-size=8192
```

Is it like Java, that we shouldn't use swap?

[source1](https://stackoverflow.com/q/41347700/9569495)
[source2](https://stackoverflow.com/q/34858289/9569495)

edit: is there a requirement that what PHP packages should be installed? AFAIK the problem is not due to this

edit: found one question relevant to AWS limiting CPU usage [source3](https://serverfault.com/q/230495)
[source4](https://www.reddit.com/r/aws/comments/5iw7gx/is_the_fact_that_lightsail_instances_are_just/)
, from source4, I think even though there is CPU burst for 100%, the RAM still isn't swapped to disk by node, doesn't matter on CPU throttling to around 30%

**Comment by wltprgm** [comment]
> Hi there,
> 
> I am testing out this lsp on two of my servers.
> 
> 1. First server, in Digital Ocean $5 plan, 1GB ram + 2GB swap
> 
> * Big project Magento 1, the RAM used by the first node process can go up to 600+MB, it finished building the cache of 37MB in /tmp/intelephense less than 1 minute.
> * New small project YIi2, cache built around 9MB
> 
> 1. Second server, AWS LightSail $3.5 plan, 512MB RAM + 3GB swap
>    
>    * Same big Magento 1 project, the RAM used is always less than 400MB, never build any cache, using 100% process like forever
>    * Same new small project Yii2, cache built around 9MB
> 
> I am on latest Debian Buster, using `neovim` with coc nvim plugin.
> 
> It looks like it doesn't use swap at all on both of my servers. I try command to increase nodeJS memory limit also unhelpful
> [source](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory)
> 
> ```
> export NODE_OPTIONS=--max_old_space_size=4096,--optimize-for-size,--max-executable-size=8192
> ```
> 
> Is it like Java, that we shouldn't use swap?
> 
> [source1](https://stackoverflow.com/q/41347700/9569495)
> [source2](https://stackoverflow.com/q/34858289/9569495)

edit: Is there a requirement, like what php package to be installed? AFAIK, likely not due to this though

**Comment by bmewburn** [comment]
I don't understand the question. Isn't swap an OS level concept? This extension has no control over that.

**Comment by wltprgm** [comment]
My question is **"is this extension written in a way to use swap memory? because from my testing, it doesn't use swap memory"**

Refer to this stackoverflow question https://stackoverflow.com/q/41347700

It's ok if you couldn't program it to use swap memory, I will just close this issue if that's the case

**Comment by bmewburn** [comment]
No I didn't program it specifically to use swap memory. AFAIK, and to quote the SO link

> It is managed by the OS. The process asks for a new page and it doesn't even know if it's swapped or not

**Comment by wltprgm** [comment]
Not sure why you ignore this part from the SO question:

> While googling, I found this article: Increasing Node.js memory limits.
> 
> The author says his server only has 8GB of physical memory, but his Nodejs process is using 28GB of memory. I assume that it is using physical + swap memory. The article also mentioned that the developer of a famous Nodejs framework uses 15GB memory limit for his Nodejs.

Similarly in another SO link: https://stackoverflow.com/q/38558989

**Comment by bmewburn** [comment]
Closing, I'm assuming for large projects it's swapping so much that it takes a very long time to build indexes. The server itself has no knowledge of swap.
