### ISSUE TITLE
intelephense will create folder on my home path

### ISSUE THREAD

**Issue by marlonfan** [bmewburn/intelephense-docs#13]
Hi~ my initialOptions is:

```
initializationOptions: {
    storagePath: '~/.config/coc/coc-phpls-data',
    clearCache: clearCache
 },
```

But will create a folder on my home path

**Comment by marlonfan** [comment]
[marlonfan/coc-phpls] (https://github.com/marlonfan/coc-phpls/issues/32)
There are some people like me

**Comment by bmewburn** [comment]
Hi @marlonfan . There's now a `globalStoragePath` property that can be passed in `initializationOptions`. If it's not present then it defaults to nodejs `os.homedir()`. I've updated the readme now to reflect this. https://github.com/bmewburn/intelephense-docs#initialisation-options

**Comment by marlonfan** [comment]
Cool. Thanks your job
