### ISSUE TITLE
Please update document

### ISSUE THREAD

**Issue by yaegassy** [bmewburn/intelephense-docs#25]
@bmewburn Thanks for this language server.

When I checked "configuration" of `vscode-intelephense`, it seems that there are many things that are not reflected in `intelephense-docs`.

e.g. `intelephense.diagnostics.*`.

Could you please update `"Configuration Options"` of intelephense-docs?

**Comment by bmewburn** [comment]
Docs are still a work in progress but the configuration schema has been updated to 1.4.0 https://github.com/bmewburn/intelephense-docs/blob/master/installation.md
