### ISSUE TITLE
Resolve untyped variables or inherited type variables

### ISSUE THREAD

**Issue by sigzegv** [bmewburn/intelephense-docs#30]
Sometimes we use Interface types to declare variable in methods parameters like `myfunction(SomeInterface $var)`, but we use derived class objects when using that method, eg `class SomeObject implements SomeInterface` and this SomeObject may have methods not declared in the interface.
After then, intelephense is not able to resolve methods from SomeObject in the code and says they're undefined. I know the correct thing should be to use an annotation with correct type, but the doctype should not indicate another type than the one declared in the method parameter (which could not be resolved)

The real question is : Is there a way to force intelephense to check a correct type for a var without an annotation (with a config solution or something like that, configured outside of source code because everything cannot be versionned)

**Comment by deevus** [comment]
There's no way that intelephense could know what concrete implementation you're using at runtime. It sounds like a problem with your code's design. 

To get around it, you could run an `instanceof` check, after which intelephense will hint the correct type. 

```php
if ($a instanceof MyClass) {
  ....
}
```

**Comment by sigzegv** [comment]
this is not a design issue if you use an Interface to define a method parameter like in my first example, because the object you pass after that may have more methods than the interface. Of course in this case the annotation can solve the issue, I was just hopping there was more way to tell intelephense to select the correct definitions.

Thank you anyway :)

**Comment by bmewburn** [comment]
You can use either
```php
/** @var ActualType $var */
```
```php
if($var instanceof ActualType) {
  //...
}
```
```php
assert($var instanceof ActualType);
//...
```
