### ISSUE TITLE
Action to implement contracts

### ISSUE THREAD

**Issue by rosmanov** [bmewburn/intelephense-docs#31]
This is a feature request. I've been using intelephense premium for about six months, and I'm almost happy with it. What makes me feel unhappy is the lack of some refactoring features I used to use with Phpactor, especially its ["Implement contracts" function](https://phpactor.readthedocs.io/en/develop/reference/refactorings.html#implement-contracts). I'd be cool if you could add this function.

Thanks.

**Comment by bmewburn** [comment]
This is available as a code action in the premium version.
