### ISSUE TITLE
Missing undefined check on initializationOptions

### ISSUE THREAD

**Issue by blackwolf12333** [bmewburn/intelephense-docs#38]
I was trying to integrate intelephense in Gnome Builder, but intelephense crashes with `Request initialize failed with message: Cannot read property 'dataPaths' of undefined`. I grepped the released intelephense code for this and found that you don't have an undefined check on `initializationOptions` before accessing `dataPaths` on it. According to the LSP spec this field does not need to be defined https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#initialize.

**Comment by twouters** [comment]
You probably want to report this on https://github.com/bmewburn/vscode-intelephense instead

**Comment by blackwolf12333** [comment]
Yeah probably good idea, reported it there.
