### ISSUE TITLE
Configuration when using ALE/Vim?

### ISSUE THREAD

**Issue by superDuperCyberTechno** [bmewburn/intelephense-docs#43]
I use ALE within Vim to take advantage of Intelephense. However, I cannot for the life of me figure out how I would pass any configuration to Intelephense.

I've noticed an (empty) folder (_intelephense_) in my home directory, could that possibly have anything to do with configuration?

**Comment by weeman1337** [comment]
You could have a look at this one: https://github.com/nathunsmitty/nvim-ale-diagnostic

→ setup intelephense as usual and it will route the diagnostic results to ALE

**Comment by superDuperCyberTechno** [comment]
I dropped ALE as soon as Neovim 0.5 launched and went for [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

I made some settings work using the following line in my init.vim:

```
lua require('lspconfig').intelephense.setup{settings = {intelephense = {diagnostics = {undefinedTypes = false, unusedSymbols = true, undefinedMethods = false}}}}
```
