### ISSUE TITLE
Failed to apply changes to file warning in Kate editor

### ISSUE THREAD

**Issue by juliardi** [bmewburn/intelephense-docs#44]
Hi @bmewburn, 

I have a problem integrating Intelephense to Kate editor. I don't know if this problem is from Kate's side or Intelephense's side, so I am opening issues here and also in Kate's side (https://bugs.kde.org/show_bug.cgi?id=439671). Here is the details of the problem.

### SUMMARY
I have installed Kate version 21.04.1 on Manjaro Linux. I also have Intelephense LSP installed and added to PATH. It can be used from other text editor such as Sublime Text, Atom, or VSCode. Intelephense can be started successfully from Kate, but failed to provide autocompletion or any other feature.

### STEPS TO REPRODUCE
1. Add Intelephense configuration to kate_lsp_client.json
2. Open PHP project folder
3. Open PHP file from project
4. Try calling autocompletion feature

### OBSERVED RESULT
17:17:01 LSP Server Warning intelephense@/home/path/to/project 
Failed to apply changes to file://home/path/to/project/src/File.php

### EXPECTED RESULT
LSP features should work

### SOFTWARE/OS VERSIONS
Linux: Manjaro with GNOME 40.1.0

ADDITIONAL INFORMATION
LSP configuration
```json
"intelephense": {
    "command": ["/usr/bin/intelephense", "--stdio"],
    "url": "https://github.com/bmewburn/intelephense-docs",
    "highlightingModeRegex": "^PHP.*$",
    "rootIndicationFileNames": ["composer.json"]
}
```

**Comment by juliardi** [comment]
Also, as an additional note, Intelephense started successfully. The warning show up when I tried the autocompletion feature.

**Comment by bmewburn** [comment]
This usually means the document is not open and in memory. A document may not have been opened if either:

* A [`didOpen` notification](https://microsoft.github.io/language-server-protocol/specification#textDocument_didOpen) was not sent from the client.
* The `didOpen` was ignored by intelephense because the document language ID was not `php`.
* The `didOpen` was ignored by intelephense because the document was too large (default 1MB).

Are you able to provide a trace of the requests/notifications sent by the client?

**Comment by juliardi** [comment]
Unfortunately, I haven't found the way to do that with Kate editor. I will update this thread when I found another clue regarding this issue.

**Comment by juliardi** [comment]
Hi @bmewburn , 
Today I realized that my intelephense version is old (version 1.4.x) and after installing version 1.7.1, I got another error message from intelephense :
```
   textDocument/didOpen ignored. file:///path/to/file.php has unsupported language ID intelephense.
```

I think this match the second scenario you mentioned, the `didOpen` was ignored by intelephense because the document language ID was not php. Kate's language information itself looks like this, so maybe they do not send it as PHP.
![image](https://user-images.githubusercontent.com/4223302/126886784-c18d3920-5922-44e5-867f-3ef25867fd81.png)

**Comment by juliardi** [comment]
I am sorry, I think the error happened because of may faulty config. I put `intelephense` instead of `php` as a key in the configuration. This is my working configuration for Kate Editor : 
```json
"php": {
    "command": ["/usr/bin/intelephense", "--stdio", "--debug"],
    "url": "https://github.com/bmewburn/intelephense-docs",
    "highlightingModeRegex": "^PHP.*$",
    "rootIndicationFileNames": ["composer.json"]
},
```
