### ISSUE TITLE
Proprietary? Since when? Is there a commercial offering now?

### ISSUE THREAD

**Issue by brad-jones** [bmewburn/intelephense-docs#5]
Long time PHP developer here, although have been on a bit of a hiatus and using other tech stacks in recent times. Anyway I am back working on a PHP project and came back to install intelephense only to discover half of it's been hidden away.

@bmewburn I understand it's your prerogative to make the underlying language server proprietary, I have no issue with that. Although I admit I was a bit taken aback at first.

It just seems like it's fallen off the planet without any discussion, no blog posts, no new announcements of a commercial offering. Unless I am just looking in all the wrong places?

Anyway it's a great product and hope there is something in the pipeline that your soon to announce to the PHP community.

**Comment by bmewburn** [comment]
Version 1.0 was released end of Feb 19 . A lot of work went into refactoring and improving 1.0 over the 0.x line. Given this and the fact that 0.x was becoming quite buggy I wanted to get a new version out there whilst keeping options open on the future direction of the project. While the licence change means the code cannot be modified and/or used by 3rd parties for commercial purposes, the product is still free to use for end users with any LSP client. The current feature set will always be free.

**Comment by Taluu** [comment]
Hi,

I get why you want to "keep options". But for the part of "preventing changes from 3rd party for commercial uses", there are open source licenses that does exactly that (BSD or GPL are such IIRC), while keeping the code open (and allowing external contribs to contribute back).

Just this message to justify my :confused: reaction. :}

**Comment by chrisphale** [comment]
Hi,

Great code @bmewburn  !

Did this change: "The current feature set will always be free....", because I just went to 
 https://intelephense.com/ and paid a tenner? 

Regards,
Chris.

**Comment by bmewburn** [comment]
Thanks for your support @chrisphale . The feature set that was available back in March 2019 is still free. Since then additional features have become available under a perpetual licence for a one off fee.

**Comment by chrisphale** [comment]
Ah, no worries. I was more concerned if I had just paid someone else for your work!

**Comment by klesun** [comment]
Does anyone have a link to the version of the code before it became proprietary? Some forks maybe? I'm about to write an [extension](https://github.com/klesun/deep-assoc-completion-vscode) that will depend on intelephense, having the source code to look at would help a lot in understanding the API.

The thing that concerns me the most is the php syntax tree parser. Did you write it yourself, or did you use some existing lib? Would be not fun at all to re-implement it again myself...
