### ISSUE TITLE
A core PHP function is undefined?

### ISSUE THREAD

**Issue by wileycoyote78** [bmewburn/intelephense-docs#53]
Hello,

Just setup VS Code and added Intelliphense extension (1.9.0). I noticed that the PHP functions [rand()](https://www.php.net/manual/en/function.rand.php) and [mt_rand()](https://www.php.net/manual/en/function.mt-rand.php) are coming up as 'undefined' by this plugin.

![image](https://user-images.githubusercontent.com/113306650/210191879-33704f32-77fb-494f-a788-1d6490b441da.png)

I tried looking for an "ignore this error" option in the plugin, but there doesn't seem to be one. I don't use these functions much, but I figured I'd let you know.

**Comment by bmewburn** [comment]
thanks tracking in https://github.com/bmewburn/vscode-intelephense/issues/2376
