### ISSUE TITLE
Server should not advertise `selectionRangeProvider` in non-registered version

### ISSUE THREAD

**Issue by rchl** [bmewburn/intelephense-docs#55]
Since intelephense only supports expanding selection range in registered version, it shouldn't advertise support for it in non-registered versions since it makes experience worse because editor won't fall back to native selection expand in that case and the server provided one doesn't make sense.

**Comment by bmewburn** [comment]
It should be declaring `capabilities.selectionRangeProvider` as `false` in this case. Do you have a trace of the response to the `initialize` request that you could post?

**Comment by rchl** [comment]
I'm sorry, you are right.
I had both intelephense and https://github.com/sublimelsp/LSP-html running at the same time in php file and it was the latter that provided silly range.
