### ISSUE TITLE
Support intersections and unions type

### ISSUE THREAD

**Issue by Taluu** [bmewburn/intelephense-docs#7]
Not sure this is the right place for such a "feature demand", but here goes.

Even though it is not really "official" per se, we can see more and more the syntax to define types using intersections and unions, such as `Collection&iterable<Foo>`, or variants such as `Collection|Foo[]`.

This doesn't seem to be supported on intelephense and reports an error (while it is supported by e.g phpstan). Would be awesome to have such a support.

Cheers.

**Comment by bmewburn** [comment]
intersection types added in 1.1
