### ISSUE TITLE
how to disable markdown format on hover or signatureHelp or everywhere?

### ISSUE THREAD

**Issue by marlonfan** [bmewburn/intelephense-docs#8]
I use intelephense for my plugin server, [client](https://github.com/marlonfan/coc-phpls) on vim, but can't suppert markdown preview, i want disable this.

**Comment by marlonfan** [comment]
https://github.com/marlonfan/coc-phpls/issues/22

**Comment by bmewburn** [comment]
The server currently ignores the client initialisation options that specify `MarkupKind` and defaults to markdown. I plan to correct this and once this has been implemented clients shouldn't have to do anything other than send the appropriate `MarkupKind` in the init options.

**Comment by marlonfan** [comment]
Got it, looking forward to it.

**Comment by bmewburn** [comment]
This will be in version 1.1
